### ISSUE TITLE
Import USWDS and add banner to very top of app

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#20]
https://designsystem.digital.gov/
We'll start with just this banner for now as far as uswds components.
![image](https://user-images.githubusercontent.com/23640741/125534705-8deabd65-f0b2-44dd-8a2c-7a49911e37c3.png)

**Comment by Abigail770** [comment]
The documentation for adding the banner wasn't very clear.  I ended up following what Streamgage National repo did and copied the code from the component on the USWDS site into a new vue file, then added the reference to the uswds css.  I just copied the images needed into our code's assets folder.  

I had to add an outer div with relative position to the rest of the content since the banner is collapsible and then absolute positioning to the sidebar and v-app-bar.  I'd like everything to fit nicely on the screen without needing a scrollbar until the banner opens, but haven't found a way to do that yet.  @lprivette do you have any tips on how to do that?

**Comment by lprivette** [comment]
Yeah USWDS documentation is definitely wanting. 

I'm not sure offhand but I will check out branch `20` when I can and see what I can figure out
