### ISSUE TITLE
Setup script on desktop on network

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#30]
- [ ] put script on computer on network 
- [ ] setup windows task to run the script every 24 hours

**Comment by lprivette** [comment]
Due to on network requirement to use AQ, we'll need to run the script from a server or desktop on network. Geoplatform hosting cannot do this.

Once the new EROS server is setup (sometime in the fall?) we'll move it there.

**Comment by lprivette** [comment]
@aaronstephenson Script has been approved and I've confirmed that I can access prod data.

Can you give me the connection info for the desktop we'll be running the script from? Or is this something someone else will have to do?

**Comment by lprivette** [comment]
@aaronstephenson Is there a estimate for when that EROS server will be available? Cooperator is curious.

**Comment by HansVraga** [comment]
I can answer this - work is in progress to set that system on now, maybe another week or two?

**Comment by lprivette** [comment]
oh nice, thanks Hans!

**Comment by lprivette** [comment]
chad provided me with creds to EROS Ubunto server.

Next steps: determine how to run the script on a 24 hr interval starting at 2 AM eastern

**Comment by aaronstephenson** [comment]
@lprivette To run a script on a regular interval, use crontab:
`crontab -e`

Add a line to the file with the schedule and the script:
`0 2 * * * /opt/my_script.sh`
(ensure the script notes which interpreter will run the script, on the first line of the script file, as a hashbang: `#! /bin/sh`, otherwise include the interpreter and its path in the crontab line)

(The schedule format is minute, hour, day (of month), month, day (of week))

We can do this for you, or you can, or we can do it together.

**Comment by lprivette** [comment]
Thank you Aaron! I would like to do it together if that's ok! Would python be considered an interpreter to run the script?

**Comment by aaronstephenson** [comment]
Sure, let's try to do it together today. Yes, python works great in this scenario. We can find appropriate locations for all the files when we meet.

**Comment by lprivette** [comment]
Deployed to EROS server
