### ISSUE TITLE
Add NWIS streamgage layer and make it toggleable via a checkbox in the sidebar

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Thresholds#6]

**Comment by Abigail770** [comment]
@lprivette we are using the same streamgage service as FEV and stnweb2, right (the site service for the markers and IV service for the graphs from here: https://waterservices.usgs.gov/rest/)?  The requests can't exceed a product of 25 degrees, so if the streamgages are loaded at the US scale, I think we would need to make multiple requests. Otherwise we could have the layer only available at a certain zoom level like FEV and stnweb.

**Comment by lprivette** [comment]
For this ticket, let's implement the same as stn/fev since it's a supporting layer that users can toggle on if they want. 

As an FYI, on another project I'm working on, they have a map (which we're actually removing in the updates we're making lol) that does display nwis sites us-wide. I haven't looked at the code for it, but I expect they are making multiple calls. It takes a while to load after you click a button to fire it off https://www.waterqualitydata.us/portal/
![image](https://user-images.githubusercontent.com/23640741/125802548-759b0ce4-671b-41c3-8b3a-99d44f6e19f9.png)

**Comment by Abigail770** [comment]
Oh nice!  Is the code for that in the WIM Github?  I'm curious to see how they're doing it.
